server:
  port: 8888

spring:
  application:
    name: SecurityTest
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://222.186.34.109:3306/security_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 183193
  data:
      redis:
        host: 222.186.34.109
        port: 8891
        password: 183193
        database: 10



